######################## default configuration ####################
baseURL = "/"
title = "AI4Bhārat"
publishDir = "docs"
languageName = "En"
languageCode = "en-in"
# post pagination
paginate = "9"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Articles"
URL = "articles"
weight = 2

[[menu.main]]
name = "Projects"
URL = "projects"
weight = 1

[[menu.main]]
name = "Support us"
URL = "join-us"
weight = 4

[[menu.main]]
name = "Events"
URL = "events"
weight = 3

#[[menu.main]]
#name = "Contact"
#URL = "contact"
#weight = 5

# organization 
[[menu.organization]]
name = "About Us"
URL = "/articles/case/"

[[menu.organization]]
name = "Active Projects"
URL = "/projects"

[[menu.organization]]
name = "Events"
URL = "/events"

# Product 
[[menu.product]]
name = "Apply to join"
URL = "/join-us"

[[menu.product]]
name = "Articles"
URL = "/articles"

[[menu.product]]
name = "Contribute Directly"
URL = "https://github.com/AI4Bharat"

# Support 
[[menu.support]]
name = "Privacy Policy"
URL = "privacy-policy"

[[menu.support]]
name = "Terms & Conditions"
URL = "terms-conditions"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_content = "Address: IIT-Madras Research Park, Taramani, Chennai-600113"
# copyright
# copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
copyright = "[Made in ❤️ with open-source by AI4Bhārat](https://github.com/AI4Bharat/ai4bharat.org)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "GitHub"
link = "https://github.com/AI4Bharat"


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/onefourthlabs"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/ai4bharat"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/showcase/ai4bharat"
